### ISSUE TITLE
Docker image fails to build on master

### ISSUE THREAD

**Issue by sharpcoder77** [GoogleCloudPlatform/jenkins-gcp-leader#2]
Build fails at following command in Dockerfile:

`COPY workflow-version.txt plugins.txt /usr/share/jenkins/plugins.txt`

Error thrown is:

When using COPY with more than one source file, the destination must be a directory and end with a /

**Comment by evandbrown** [comment]
Sorry for the slow reply here. This should be working OK now. Thanks!
