### ISSUE TITLE
latest is still missing

### ISSUE THREAD

**Issue by codepj** [GoogleCloudPlatform/jenkins-gcp-leader#3]
"Tag latest not found in repository gcr.io/cloud-solutions-images/jenkins-gcp-leader"

**Comment by evandbrown** [comment]
I've pulled the :latest tag in favor of revving image versions in the project that uses these images, specifically https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/images.cfg.

Thanks!
